name: memory
recipe: drupal10
excludes:
  - drush
  - web/themes/contrib
  - web/profiles
  - node_modules
  - themesrc/node_modules
config:
  webroot: web
  php: "8.1"
  composer_version: 2
services:
  appserver:
    xdebug: true
    config:
      php: .lando.php.ini
    overrides:
      environment:
        XDEBUG_MODE:
        LANDO_HOST_IP: "172.17.0.1"
      extra_hosts:
        - ${LANDO_HOST_NAME_DEV:-host}:${LANDO_HOST_GATEWAY_DEV:-host-gateway}
    build:
      # Run composer install.
      - composer install
tooling:
  drop-tables:
    service: database
    cmd: mysql -uuser -puser www < /app/scripts/mysql/drop-tables.sql
  xdebug-on:
    service: appserver
    description: Enable xdebug for Apache.
    cmd: docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Enabling xdebug"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for Apache.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Disabling xdebug"
    user: root
  grumphp:
    service: appserver
    cmd: php /app/vendor/bin/grumphp run
